- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sushy-tempest-partition-bios-redfish-pxe
        - sushy-tempest-partition-uefi-redfish-vmedia
    gate:
      jobs:
        - sushy-tempest-partition-bios-redfish-pxe
        - sushy-tempest-partition-uefi-redfish-vmedia
