- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sushy-tempest-ironic-partition-redfish-src
        - sushy-tempest-ironic-partition-redfish-src-python2
    gate:
      jobs:
        - sushy-tempest-ironic-partition-redfish-src
        - sushy-tempest-ironic-partition-redfish-src-python2
